/* Effetti sonori generati dal browser (Web Audio) */

(function(){
  var _ac=null;
  function AC(){if(MUTED())return null;if(!_ac){try{_ac=new (window.AudioContext||window.webkitAudioContext)();}catch(e){_ac=null;}}if(_ac&&_ac.state==='suspended'){try{_ac.resume();}catch(e){}}return _ac;}
  function noiseBuf(ac,dur,pw){var sr=ac.sampleRate,buf=ac.createBuffer(1,Math.floor(sr*dur),sr),d=buf.getChannelData(0);for(var i=0;i<d.length;i++){d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,pw);}return buf;}
  function irBuf(ac,dur,decay){var sr=ac.sampleRate,len=Math.max(1,Math.floor(sr*dur)),buf=ac.createBuffer(2,len,sr);for(var ch=0;ch<2;ch++){var d=buf.getChannelData(ch);for(var i=0;i<len;i++){d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay);}}return buf;}
  function sfxClick(){var ac=AC();if(!ac)return;var t=ac.currentTime;var o=ac.createOscillator(),g=ac.createGain();o.type='triangle';var _cp=0.93+Math.random()*0.14;o.frequency.setValueAtTime(1240*_cp,t);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.05,t+0.001);g.gain.exponentialRampToValueAtTime(0.0001,t+0.045);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+0.055);var o2=ac.createOscillator(),g2=ac.createGain();o2.type='sine';o2.frequency.setValueAtTime(2480*_cp,t);g2.gain.setValueAtTime(0.0001,t);g2.gain.exponentialRampToValueAtTime(0.022,t+0.001);g2.gain.exponentialRampToValueAtTime(0.0001,t+0.028);o2.connect(g2);g2.connect(ac.destination);o2.start(t);o2.stop(t+0.04);var ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,0.02,4);var bp=ac.createBiquadFilter();bp.type='bandpass';bp.frequency.value=2600;bp.Q.value=0.8;var ng=ac.createGain();ng.gain.setValueAtTime(0.0001,t);ng.gain.exponentialRampToValueAtTime(0.025,t+0.0006);ng.gain.exponentialRampToValueAtTime(0.0001,t+0.008);ns.connect(bp);bp.connect(ng);ng.connect(ac.destination);ns.start(t);}
  function sfxBoom(intensity){var ac=AC();if(!ac)return;intensity=intensity||0.5;var t=ac.currentTime;var conv=ac.createConvolver();conv.buffer=irBuf(ac,1.5,2.5);var wet=ac.createGain();wet.gain.value=0.4*intensity;conv.connect(wet);wet.connect(ac.destination);var dur=0.95;var ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,dur,2);var lp=ac.createBiquadFilter();lp.type='lowpass';lp.frequency.setValueAtTime(900,t);lp.frequency.exponentialRampToValueAtTime(120,t+0.6);var ng=ac.createGain();ng.gain.setValueAtTime(0.0001,t);ng.gain.exponentialRampToValueAtTime(0.16*intensity,t+0.02);ng.gain.exponentialRampToValueAtTime(0.0001,t+dur);ns.connect(lp);lp.connect(ng);ng.connect(ac.destination);ng.connect(conv);ns.start(t);var o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(110,t);o.frequency.exponentialRampToValueAtTime(38,t+0.7);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.14*intensity,t+0.03);g.gain.exponentialRampToValueAtTime(0.0001,t+0.85);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+0.9);}
  function sfxMasterClick(){var ac=AC();if(!ac)return;var t=ac.currentTime;var o=ac.createOscillator(),g=ac.createGain(),f=ac.createBiquadFilter();o.type='sawtooth';o.frequency.setValueAtTime(160,t);o.frequency.exponentialRampToValueAtTime(70,t+0.18);f.type='lowpass';f.frequency.value=600;g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.07,t+0.01);g.gain.exponentialRampToValueAtTime(0.0001,t+0.3);o.connect(f);f.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+0.32);}
  function sfxLock(){var ac=AC();if(!ac)return;var t=ac.currentTime;var freqs=[55,58.5,82];for(var k=0;k<freqs.length;k++){var o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.value=freqs[k];g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.05,t+0.7);g.gain.exponentialRampToValueAtTime(0.0001,t+2.6);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+2.7);}var ct=t+0.5,ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,0.28,3);var bp=ac.createBiquadFilter();bp.type='bandpass';bp.frequency.value=180;bp.Q.value=2;var ng=ac.createGain();ng.gain.setValueAtTime(0.0001,ct);ng.gain.exponentialRampToValueAtTime(0.09,ct+0.008);ng.gain.exponentialRampToValueAtTime(0.0001,ct+0.27);ns.connect(bp);bp.connect(ng);ng.connect(ac.destination);ns.start(ct);}
  function sfxSigil(){var ac=AC();if(!ac)return;var t=ac.currentTime;var notes=[196,262,330,392];for(var k=0;k<notes.length;k++){var o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(notes[k]*0.75,t);o.frequency.exponentialRampToValueAtTime(notes[k],t+1.8);var st=t+k*0.2;g.gain.setValueAtTime(0.0001,st);g.gain.exponentialRampToValueAtTime(0.033,st+0.6);g.gain.exponentialRampToValueAtTime(0.0001,st+3);o.connect(g);g.connect(ac.destination);o.start(st);o.stop(st+3.1);}var o2=ac.createOscillator(),g2=ac.createGain();o2.type='triangle';o2.frequency.setValueAtTime(660,t);o2.frequency.linearRampToValueAtTime(880,t+2.4);g2.gain.setValueAtTime(0.0001,t);g2.gain.setValueAtTime(0.0001,t+0.4);g2.gain.exponentialRampToValueAtTime(0.014,t+1.4);g2.gain.exponentialRampToValueAtTime(0.0001,t+3);o2.connect(g2);g2.connect(ac.destination);o2.start(t);o2.stop(t+3.1);}
  function sfxBurst(){var ac=AC();if(!ac)return;var t=ac.currentTime;var dur=0.8,ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,dur,1.6);var bp=ac.createBiquadFilter();bp.type='bandpass';bp.frequency.setValueAtTime(800,t);bp.frequency.exponentialRampToValueAtTime(260,t+0.55);bp.Q.value=0.7;var ng=ac.createGain();ng.gain.setValueAtTime(0.0001,t);ng.gain.exponentialRampToValueAtTime(0.07,t+0.02);ng.gain.exponentialRampToValueAtTime(0.0001,t+dur);ns.connect(bp);bp.connect(ng);ng.connect(ac.destination);ns.start(t);var ch=[262,330,392,523];for(var k=0;k<ch.length;k++){var o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.value=ch[k];g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.034,t+0.04);g.gain.exponentialRampToValueAtTime(0.0001,t+1.1);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+1.2);}var o2=ac.createOscillator(),g2=ac.createGain();o2.type='sine';o2.frequency.setValueAtTime(95,t);o2.frequency.exponentialRampToValueAtTime(45,t+0.4);g2.gain.setValueAtTime(0.0001,t);g2.gain.exponentialRampToValueAtTime(0.08,t+0.02);g2.gain.exponentialRampToValueAtTime(0.0001,t+0.6);o2.connect(g2);g2.connect(ac.destination);o2.start(t);o2.stop(t+0.65);}
  function sfxVortex(){var ac=AC();if(!ac)return;var t=ac.currentTime,dur=6.8;var mg=ac.createGain();mg.gain.setValueAtTime(0.0001,t);mg.gain.exponentialRampToValueAtTime(0.07,t+1.4);mg.gain.setValueAtTime(0.07,t+dur-2.4);mg.gain.exponentialRampToValueAtTime(0.0001,t+dur);var lp=ac.createBiquadFilter();lp.type='lowpass';lp.frequency.value=430;mg.connect(lp);lp.connect(ac.destination);var trem=ac.createGain();trem.gain.value=0.62;var lfo=ac.createOscillator(),lfoG=ac.createGain();lfo.type='sine';lfo.frequency.setValueAtTime(0.5,t);lfo.frequency.linearRampToValueAtTime(0.9,t+dur);lfoG.gain.value=0.5;lfo.connect(lfoG);lfoG.connect(trem.gain);trem.connect(mg);lfo.start(t);lfo.stop(t+dur+0.05);var fr=[58,87,116],ty=['sine','sine','triangle'],gn=[0.46,0.28,0.13];for(var i=0;i<fr.length;i++){var o=ac.createOscillator(),g=ac.createGain();o.type=ty[i];o.frequency.setValueAtTime(fr[i],t);o.frequency.linearRampToValueAtTime(fr[i]*0.94,t+dur);g.gain.value=gn[i];o.connect(g);g.connect(trem);o.start(t);o.stop(t+dur+0.1);}var ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,dur+0.2,0.6);var bp=ac.createBiquadFilter();bp.type='bandpass';bp.Q.value=0.8;bp.frequency.setValueAtTime(220,t);bp.frequency.linearRampToValueAtTime(420,t+dur*0.5);bp.frequency.linearRampToValueAtTime(180,t+dur);var ng=ac.createGain();ng.gain.value=0.05;ns.connect(bp);bp.connect(ng);ng.connect(trem);ns.start(t);}
  function MUTED(){try{return localStorage.getItem("tcj_sfx")==="0"}catch(e){return false}}
  function tn(ac,t,f,type,dur,vol,f2){var o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(f2)o.frequency.exponentialRampToValueAtTime(f2,t+dur);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+0.012);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);o.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+dur+0.03);}
  function nz(ac,t,dur,vol,ft,f,q,pw){var ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,dur,pw||1.5);var fl=ac.createBiquadFilter();fl.type=ft;fl.frequency.value=f;fl.Q.value=q||0.8;var g=ac.createGain();g.gain.value=vol;ns.connect(fl);fl.connect(g);g.connect(ac.destination);ns.start(t);}
  function tf(ac,t,f,type,dur,vol,f2,cut){var o=ac.createOscillator(),g=ac.createGain(),fl=ac.createBiquadFilter();o.type=type;fl.type="lowpass";fl.frequency.value=cut;o.frequency.setValueAtTime(f,t);if(f2)o.frequency.exponentialRampToValueAtTime(f2,t+dur);g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+0.03);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);o.connect(fl);fl.connect(g);g.connect(ac.destination);o.start(t);o.stop(t+dur+0.03);}
  function sw(ac,t,dur,vol,type,f1,f2,q,pw){var ns=ac.createBufferSource();ns.buffer=noiseBuf(ac,dur+.05,pw);var fl=ac.createBiquadFilter();fl.type=type;fl.Q.value=q;fl.frequency.setValueAtTime(f1,t);fl.frequency.exponentialRampToValueAtTime(f2,t+dur);var g=ac.createGain();g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+dur*.35);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);ns.connect(fl);fl.connect(g);g.connect(ac.destination);ns.start(t);}
  var X={
   coin:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,1568,"square",.08,.016);tn(ac,t+.07,2093,"square",.4,.02);tn(ac,t+.07,4186,"sine",.3,.007);},
   drop:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,520,"triangle",.14,.05,230);nz(ac,t,.1,.05,"lowpass",600,.7,2);},
   dice:function(){var ac=AC();if(!ac)return;var t=ac.currentTime,i;for(i=0;i<6;i++)nz(ac,t+i*.06+Math.random()*.025,.035,.07,"bandpass",1500+Math.random()*2200,2.5,1);tn(ac,t+.42,1760,"triangle",.09,.03);},
   crack:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;nz(ac,t,.1,.14,"bandpass",3200,.6,.5);tn(ac,t,170,"sine",.22,.12,55);nz(ac,t+.05,.22,.05,"lowpass",700,.7,2);},
   mend:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,880,"triangle",.12,.03);tn(ac,t+.08,1320,"triangle",.22,.03);tn(ac,t+.08,2640,"sine",.15,.008);},
   spawn:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tf(ac,t,95,"sawtooth",.6,.07,46,380);tf(ac,t+.06,142,"sawtooth",.5,.04,68,320);nz(ac,t,.6,.05,"lowpass",240,.6,1);},
   swish:function(){var ac=AC();if(!ac)return;sw(ac,ac.currentTime,.26,.06,"bandpass",500,3400,1.2,.4);},
   wave:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;sw(ac,t,.9,.09,"lowpass",350,1100,.7,.2);sw(ac,t+.45,.9,.05,"lowpass",1000,300,.7,.2);},
   on:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,660,"triangle",.08,.035);tn(ac,t+.06,990,"triangle",.12,.035);},
   off:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,990,"triangle",.08,.03);tn(ac,t+.06,660,"triangle",.12,.03);},
   deny:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tf(ac,t,210,"sawtooth",.16,.05,150,700);tf(ac,t+.17,150,"sawtooth",.26,.05,100,600);},
   clang:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;[[520,.7,.05],[1340,.5,.03],[2190,.35,.02],[3100,.22,.012]].forEach(function(p){tn(ac,t,p[0],"sine",p[1],p[2])});nz(ac,t,.05,.08,"highpass",4500,.6,1);},
   bell:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;[0,.45].forEach(function(d){[[660,1.6,.05],[1320,1.1,.03],[1850,.8,.018],[2710,.5,.01]].forEach(function(p){tn(ac,t+d,p[0],"sine",p[1],p[2])});});},
   seal:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,95,"sine",.35,.13,42);nz(ac,t,.22,.12,"lowpass",320,.7,2);tn(ac,t+.09,1318,"sine",1.1,.022);tn(ac,t+.12,1975,"sine",.7,.012);},
   paper:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;nz(ac,t,.32,.07,"bandpass",2400,.7,.8);nz(ac,t+.1,.22,.035,"highpass",4200,.6,1);},
   charge:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,380,"sine",.14,.06,760);for(var i=0;i<3;i++)tn(ac,t+.06+i*.07+Math.random()*.03,900+Math.random()*600,"sine",.06,.022,1500+Math.random()*500);},
   crown:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;[523,659,784,1047,1319].forEach(function(f,i){tn(ac,t+i*.07,f,'sine',1.2-i*.1,.03)});tn(ac,t+.35,2093,'triangle',1.4,.012);nz(ac,t,.6,.03,'highpass',5000,.5,1);},
   tick:function(){var ac=AC();if(!ac)return;tn(ac,ac.currentTime,2200,"triangle",.05,.018);},
   gong:function(){var ac=AC();if(!ac)return;var t=ac.currentTime;tn(ac,t,98,"sine",3.2,.14);tn(ac,t,196.5,"sine",2.4,.07);tn(ac,t,293,"triangle",1.8,.03);tn(ac,t,61,"sine",2.8,.08);nz(ac,t,.6,.07,"lowpass",220,.7,2);},
   orb:function(el){var ac=AC();if(!ac)return;var t=ac.currentTime,i;
    if(el==="glaciale"){[1568,2093,2637,3136].forEach(function(f,i){tn(ac,t+i*.06,f,"triangle",.7,.018)});}
    else if(el==="ardente"){nz(ac,t,.7,.07,"bandpass",650,.5,.6);for(i=0;i<7;i++)nz(ac,t+Math.random()*.6,.03,.05,"highpass",3200,.7,1);tn(ac,t,120,"sawtooth",.35,.015,70);}
    else if(el==="folgorante"){tn(ac,t,1900,"square",.2,.02,260);nz(ac,t,.16,.05,"highpass",2600,.6,1);tn(ac,t+.12,1400,"square",.1,.012,300);}
    else if(el==="terrestre"){tn(ac,t,140,"sine",.45,.09,85);tf(ac,t,300,"triangle",.42,.095,160,1400);tf(ac,t+.02,450,"sawtooth",.28,.05,240,1100);nz(ac,t,.3,.12,"bandpass",900,.9,1.6);for(i=0;i<6;i++)nz(ac,t+.03+Math.random()*.32,.035,.07,"bandpass",1600+Math.random()*1800,2,1);}
    else if(el==="radiante"){[784,988,1175,1568].forEach(function(f,i){tn(ac,t+i*.035,f,"sine",1.1,.016)});}
    else if(el==="oscuro"){tn(ac,t,110,"sine",1.1,.05,55);tf(ac,t,330,"sawtooth",1.2,.05,165,800);tf(ac,t,349,"sawtooth",1.1,.04,175,760);tn(ac,t+.05,466,"triangle",.8,.022,233);sw(ac,t,.95,.09,"bandpass",900,240,1.4,.5);}}
  };
  window.__sfx=X;
  window.__sfxBoom=sfxBoom;window.__sfxLock=sfxLock;window.__sfxSigil=sfxSigil;window.__sfxBurst=sfxBurst;window.__sfxClick=sfxClick;window.__sfxVortex=sfxVortex;
  document.addEventListener('click',function(e){var el=e.target;if(el&&el.closest){if(el.closest('#intro')||el.closest('#munlock'))return;if(el.closest('#mbtn')){sfxMasterClick();return;}}sfxClick();},true);
})();

