/* Schede dei continenti nella sezione Mappa */
const CONT_DATA={
  ardente:{name:"Continente Ardente",capital:"Nuova Amorgoth",ruler:"Rebenek Wkor & Jsur Lume",icon:"🔥",color:"var(--fire)",bg:"rgba(224,90,32,.12)",lore:"Due tribù Krolachi convivono dopo aver perso le proprie capitali: gli <strong>Amorlarien</strong> (guerrieri viscerali, combattono per la gioia di combattere) e i <strong>Gothzian</strong> (calcolatori e schivi, seguono rigide convenzioni sociali). Un'alleanza militare con le isole congelanti è in corso di negoziazione per riconquistare i territori perduti agli Silver. Gli <strong>Alchimisti di Guerra</strong> e gli <strong>Artigli Brucianti</strong> operano nelle zone più remote.",detail:null},
  terrestre:{name:"Continente Terrestre",capital:"Greenshard",ruler:"Revelor Baalz",icon:"🌍",color:"var(--earth)",bg:"rgba(139,104,64,.12)",lore:"Due anime: gli <strong>Slayer di Frontiera</strong> (aperti e pacifici, con base a Greenshard) e i <strong>Custodi di Rovo</strong> (radicali che non tollerano estranei, abitano sugli alberi senza toccare il suolo). La scissione risale alla disputa tra Ennea e Corrag, figli di Ermonium Baalz. I Custodi di Rovo subiscono la minaccia crescente dell'<strong>Agarus</strong>, il behemoth leggendario terrestre le cui spore avvelenano l'area circostante.",detail:null},
  folgorante:{name:"Continente Folgorante",capital:"Ostia",ruler:"Godrik E. Tasher",icon:"⚡",color:"var(--lightning)",bg:"rgba(240,208,32,.1)",lore:"Una distopia steampunk industriale governata con pugno di ferro dalle <strong>Guardie di Ostia</strong>. I <strong>TecnoSlayer</strong> — robot che mimano le capacità degli Slayer — sono prodotti in massa da Godrik. I ribelli <strong>Eroi di Ostia</strong> sabotano le fabbriche senza fare vittime: il loro scopo è fermare l'espansionismo del continente e lo sviluppo militare spinto voluto dal regime. Sopravvive la scuola dei <strong>Monaci del Pugno</strong>, di cui faceva parte la Maestra Sfregiata.",detail:"Ispirazione: distopia steampunk industriale"},
  radiante:{name:"Continente Radiante",capital:"Rupenigma",ruler:"Pirati & Cultisti",icon:"✨",color:"var(--radiant)",bg:"rgba(212,168,255,.1)",lore:"Una terra desolata: altopiani di rocce secche dominati dai pirati nelle zone periferiche. Le leggende parlano dei <strong>Solcavuoto</strong> — una civiltà antica dalla conoscenza straordinaria. I <strong>Paradossisti</strong> (guardano al futuro) e i <strong>Primordialisti</strong> (custodi del passato) sopravvivono nell'interno. A <strong>Rupenigma</strong> si dice sia nascosto l'ultimo portale verso la Soglia Crepuscolare.",detail:"Terra di Nessuno"},
  glaciale:{name:"Continente Glaciale",capital:"NetherWinter",ruler:"Ragnar Silver",icon:"❄️",color:"var(--ice)",bg:"rgba(126,200,227,.1)",lore:"Dominate dalla monarchia assoluta della <strong>Famiglia Silver</strong>, guidata dal tiranno <strong>Ragnar Silver</strong>. Un tempo regno cosmopolita e aperto, si è trasformato in uno stato militarista nell'arco di cinque decadi. Il regime mantiene un accordo con le Guardie di Ostia per lo scambio di tecnologie militari e controlla parti delle isole ardenti e radianti.",detail:"Ispirazione culturale: Medioevo occidentale europeo"},
  oscuro:{name:"Continente Oscuro",capital:"Zoa Shia",ruler:"Famiglia Grimstone",icon:"🌑",color:"var(--dark)",bg:"rgba(136,96,208,.12)",lore:"Avvolti nell'oscurità dell'aether oscuro, governati da un sistema feudale basato sul baratto. Il prestigio dipende dalle capacità dimostrabili. Famiglie principali: <strong>Zeraora, Grimstone, Val’Riden, Monkuiced</strong>. Due casate possiedono una compagnia di Slayer, ma ne vendono i servizi a chiunque possa pagarli: gli <strong>Slayer Fatui</strong> dei <strong>Monkuiced</strong> — uniformi a fiamme violacee — lavorano a contratto senza curarsi di essere visti; gli <strong>Slayer Ombra</strong> dei <strong>Val’Riden</strong> costano assai di più e non li vede mai nessuno.",detail:"Ispirazione: Medioevo giapponese, cinese e mongolo"},
  ramsgate:{name:"Ramsgate",capital:"Ramsgate",ruler:"Estarossa (Mael dell'Aether Terrestre)",icon:"🏰",color:"#c8a84b",bg:"rgba(139,90,43,.12)",lore:"Città simbolo degli Slayer, distrutta durante il cataclisma del Tradimento di Gabrael e ricostruita sulle sue rovine. Cosmopolita per eccellenza: luogo di incontro per avventurieri, rifugiati e mercanti di ogni regione. Ramsgate regola il rilascio del titolo ufficiale di Slayer. L'unica zona vietata è l'isola della <strong>Vecchia Ramsgate</strong>: le scariche di aether puro la rendono altamente instabile.",detail:"Baluardo degli Slayer"}
};
