/* Manuale: armi, celle, Omnicelle e amplificatori */
const WD=[
  {n:"Spada",t:"Bilanciata · Mirato",tr:["1D6","2D6","3D6","4D6","6D6"],ch:"4-5 (1c) / 6 (2c)",sp:[{n:"Onda Lama",d:"Vicino: +dado extra +4. A distanza: attacco ignorando distanza +dado."},{n:"Parata",d:"Vicino: nega danno, poi attacca con dadi +1 +4. A distanza: ignora attacchi a distanza."},{n:"Eco della Forgia",d:"Zona 3×3: Behemoth entrando subisce dado danno +4."}]},
  {n:"Lancia",t:"Bilanciata · Lacerante",tr:["1D6","2D6","3D6","4D6","6D6"],ch:"4-5 (1c) / 6 (2c)",sp:[{n:"Proiettile Aetherico",d:"Vicino: +dado extra +4. A distanza: attacco ignorando distanza +dado."},{n:"Balzo Spericolato",d:"Vicino: nega danno, allontana 6 quadretti. A distanza: avvicina 2× spostamento, 2 dadi +4."},{n:"Carica Rivalsa",d:"Avvicini ignorando distanza: 1 dado +4 fisso +1 ogni 2 quadretti."}]},
  {n:"Martello",t:"Pesante · Stordente",tr:["1D8","2D8","3D8","4D8","6D8"],ch:"6-7 (1c) / 8 (2c)",sp:[{n:"Squarciaterra Rovinoso",d:"Esplosione aetherica: danno base +1 dado +4 stordente."},{n:"Cannone Aetherico",d:"Bonus FOR +8 danni stordenti senza consumare l'azione di attacco."}]},
  {n:"Ascia",t:"Pesante · Stordente + Lacerante",tr:["1D8","2D8","3D8","4D8","6D8"],ch:"6-7 (1c) / 8 (2c)",sp:[{n:"Mietitura Aetherica",d:"Lanci l'ascia: +1 dado +2 stordente. TirSalv DES per riprenderla; successo → +4 att. successivo."},{n:"Lancio Rovinoso",d:"Lanci l'ascia: +1 dado +2 lacerante. TirSalv DES; successo → +4 lacerante turno successivo."}]},
  {n:"Pugni Aetherici",t:"Leggera · Mirato + Stordente",tr:["1D4","2D4","3D4","4D4","6D4"],ch:"3 (1c) / 4 (2c)",bm:"Utilizzabile solo in presenza di un Behemoth. In prossimità garantisce bonus a seconda delle cariche: 0 cariche → teletrasporto; 1 carica → +2 tipologia di attacco; 2 cariche → −4 COST Behemoth.",sp:[{n:"Schianto Titanico",d:"In prossimità: 2 dadi extra +4 danni stordenti."},{n:"Laser Aetherico",d:"1 dado extra +6 danno mirato. Maggiore la distanza, maggiore la CD."}]},
  {n:"Lame a Catena",t:"Leggera · Lacerante + Mirato",tr:["1D4","2D4","3D4","4D4","6D4"],ch:"3-4 (1c)",bm:"Utilizzabile solo in presenza di un Behemoth. Teletrasporto: in prossimità sposta dalla parte opposta; oppure riduce la distanza di uno spostamento completo, concedendo vantaggio al prossimo tiro.",sp:[{n:"Schianto Rovinoso",d:"A distanza spostamento: 1 dado extra alla parte scelta, −4 alle altre vicine."},{n:"Slancio Rovinoso",d:"A distanza spostamento: 1 dado extra +4 lacerante, spostandoti dalla parte opposta."}]}
];
const CD={"Celle di Forza — Offensiva":[{n:"Re del Knockout",p3:"×1.5 danni vs storditi",p6:"×2 danni vs storditi"},{n:"Cacciatore di Aether",p3:"×1.5 danni vs aethercaricati",p6:"×2 danni vs aethercaricati"},{n:"Cacciatore Furioso",p3:"×1.5 danni vs infuriati",p6:"×2 danni vs infuriati"},{n:"Lavoro di Squadra",p3:"+2 danni; bonus agli alleati sullo stesso bersaglio",p6:"+4 danni; alleati ottengono vantaggio"},{n:"Incremento Aetherico",p3:"+1 token elementale",p6:"+2 token elementali"},{n:"Tempesta di Lame",p3:"Attacco mirato ×1.2",p6:"Attacco mirato ×1.5"},{n:"Sopraffazione",p3:"Attacco stordente ×1.2",p6:"Attacco stordente ×1.5"},{n:"Acido",p3:"Attacco lacerante ×1.2",p6:"Attacco lacerante ×1.5"}],"Celle di Vigore — Sopravvivenza":[{n:"Ignifuga",p3:"Immune a SCOTTATO",p6:"Immune a BRUCIATO"},{n:"Antigelo",p3:"Immune a CONGELATO",p6:"Immune a IBERNATO"},{n:"Isolante",p3:"Immune a ELETTRIFICATO",p6:"Immune a FULMINATO"},{n:"Ferreo",p3:"Immune a INTERRATO",p6:"Immune a DRENATO"},{n:"Benedetto",p3:"CORROTTO dimezzato",p6:"Immune a CORROTTO"},{n:"Marchiato",p3:"ABBAGLIATO dimezzato",p6:"Immune a ABBAGLIATO"},{n:"Coagulante",p3:"Immune a SANGUINATO",p6:"Immune a EMORRAGICO"},{n:"Corazzato",p3:"STORDITO dimezzato",p6:"Immune a STORDITO"}],"Celle di Tecnica — Stile di gioco":[{n:"Agilità",p3:"+2 caselle movimento",p6:"+4 caselle movimento"},{n:"Granpasso",p3:"Schivando: 2 danni al Behemoth",p6:"Schivando: 4 danni al Behemoth"},{n:"Medico",p3:"Alleato a terra → metà PV",p6:"Alleato a terra → tutti PV; prima caduta automatica a metà PV"},{n:"Rammendo",p3:"Oggetti curativi +4 PV extra",p6:"Oggetti curativi si attivano due volte; puoi ritirare gli 1"},{n:"Astuzia",p3:"5° attacco: critico automatico",p6:"I 2 valori più alti del dado valgono il massimo"},{n:"Riciclo",p3:"Stessa parte 3×: 3° colpo automatico",p6:"Stessa parte 2×: 2° colpo automatico"},{n:"Parassita",p3:"Sotto ¼ PV: prossimo attacco dimezzato",p6:"Sotto ¼ PV: prossimo attacco annullato"},{n:"Catalizzatore",p3:"Strumenti non curativi: durata +50%",p6:"Durata +50%, 50% di non consumare l'oggetto"}]};
const OD=[
  {n:"Risorgimento",ae:"Terrestre",tag:"tt",col:"var(--earth)",eff:["Tutti gli alleati presenti sul campo recuperano interamente i propri Punti Vita.","Riassetto completo: ogni stato alterato viene rimosso (i consumabili già usati restano consumati).","Gli alleati caduti vengono rimessi in piedi con metà dei PV massimi.","Immunità allo Stordimento per il turno in corso."]},
  {n:"Controllo",ae:"Glaciale",tag:"tg",col:"var(--ice)",eff:["Scegli un bersaglio (te stesso o un alleato, anche a grande distanza).","Per 2 turni il bersaglio è completamente immune a qualsiasi danno o effetto negativo.","Se il bersaglio sei tu e continui ad attaccare, il danno delle tue armi diventa Radiante per la durata.","Utilizzabile anche fuori combattimento come controllo completo sullo stato di un alleato."]},
  {n:"Disciplina",ae:"Ardente",tag:"ta",col:"var(--fire)",eff:["Si attiva come reazione nel momento in cui subisci un attacco.","Non subisci alcun danno da quell'attacco.","Il danno viene riflesso al Behemoth come danno Ardente, applicando Bruciato.","Il turno del Behemoth viene interrotto: Stordimento garantito, senza tiro salvezza."]},
  {n:"Tempesta",ae:"Folgorante",tag:"tf",col:"var(--lightning)",eff:["Ti avvicini al Behemoth fino a distanza doppia del tuo spostamento (conta come movimento).","Tiri 20D6 di danno Folgorante totale.","Il danno si divide equamente tra tutte le parti ancora integre del Behemoth.","Le parti già rotte non vengono conteggiate nella divisione."]},
  {n:"Legame",ae:"Oscuro",tag:"to",col:"var(--dark)",eff:["Il Behemoth bersaglio viene bloccato sul posto per il turno in corso, subendo 5D6 danno Oscuro.","Tutto il party ottiene Vantaggio ai tiri per colpirlo durante il blocco.","Per mantenerlo, spendi la tua azione bonus ogni turno: CD 15, +3 ad ogni turno successivo.","Se il tiro fallisce, il blocco termina immediatamente."]},
  {n:"Paradosso",ae:"Radiante",tag:"tr",col:"var(--radiant)",eff:["Il tempo viene riavvolto di 2 turni completi per l'intero party.","Tutti gli Slayer ottengono Vantaggio a colpire e schivare, consapevoli di ciò che sta per accadere.","Il Behemoth ripete le stesse azioni della prima volta, mantenendo tutti i danni e stati subiti.","Chi ha attivato l'abilità rimuove ogni suo stato alterato; se sotto metà PV, sale esattamente a metà."]}
];
const AMPD=[
  ["Impatto Virulento","Dopo ogni colpo critico, infliggi il 50% del danno critico appena inflitto anche a tutti gli altri Behemoth presenti sul campo."],
  ["Benedizione del Paladino","Schivare attraverso un attacco nemico concede +3 di danno a tutti gli Slayer per 1 turno."],
  ["Flusso Curativo","Schivare attraverso un attacco nemico cura fino a 2D6 PV all'alleato con meno salute."],
  ["Grido dell'Eroe","Quando uno Slayer cade: tutti i vivi ottengono uno scudo pari al 50% dei loro PV."],
  ["Dalle Ceneri","Una volta per round: quando saresti abbattuto, sopravvivi con 20 PV e rigenerazione pari all'attacco eseguito."],
  ["Ultimi Secondi","Dopo aver subito un attacco: il 50% del danno è immediato, il restante 50% alla fine del tuo turno."],
  ["Sogno Curativo","Mentre sei atterrato: curi continuamente l'alleato con meno PV di 2D6."],
  ["Tattiche di Branco","Dopo aver interrotto un Behemoth: tutti gli Slayer guadagnano +4 di velocità di movimento per 1 turno."],
  ["Robusto","+50 PV temporanei."],
  ["Frenesia di Strega","I tonici della salute hanno lo stesso effetto di tutti i tonici base assieme."],
  ["Precisione Chirurgica","Rompere una parte consente un critico garantito al prossimo attacco."],
  ["Forma Elementale: Terrestre","Schivando un attacco Behemoth, tutti i player recuperano 2D6 punti vita."],
  ["Avatar della Corruzione","Subire la forma più avanzata di uno stato alterato dona +5 danni e riduce l'effetto a quello precedente, fino a fine effetto."],
  ["Mantello Tonante / Oscuro","Consumare completamente il movimento prima di un attacco causa 2 token elementali aggiuntivi al mostro, se colpito."],
  ["Colpo Rovente","A 10+ caselle dal Behemoth, evochi una sfera elementale: 1 token elementale aggiuntivo se lanciata contro il bersaglio (azione bonus)."],
  ["Sferzata del Vuoto","Sparare un proiettile a un Behemoth aumenta di uno i token elementali subiti."],
  ["Sfera Scudante","Entro 2 caselle dal Behemoth: generi 20 PV temporanei. Non cumulabile."],
  ["Colpi Zelanti","Ogni colpo sparato a un nemico non-Behemoth: tira 1D8. Con un risultato di 8, il bersaglio viene atterrato istantaneamente."],
  ["Occhio del Parafulmine","Ogni pilone piazzato spara automaticamente un proiettile elementale al bersaglio scelto dal player."],
  ["Santuario Invernale","Se un Behemoth entra nell'area di un pilone, subisce 1D4 danni e un token elementale aggiuntivo."],
  ["Eco del Fiore","Gli effetti dei proiettili sono raddoppiati nel danno e nella durata."]
];
