/* Zona Master: schede di Mael, Alti Maestri e Maestri Minori */
const MD=[
  {nm:"Estarossa",ae:"Terrestre",rl:"Controllore · Supporto",hp:530,ac:"#a07830",s:{FOR:20,DES:26,COST:46,INT:40,SAG:50,CAR:44},wf:"Le Fondamenta di Ramsgate (Pugni Aetherici, Support)",mech:[["Zona Aetherica","Proietta una zona 5×5: chiunque dentro subisce 1D8/turno, convertiti in PV per un alleato a scelta."],["Divincolarsi","Tiro per liberarsi. Successo: esce ma con velocità dimezzata."],["Limite","Una sola zona per volta. Può spostarla liberamente nel proprio turno."]],ar:"Corona del Capricus",ad:"Bersaglio singolo, 1 turno. Tiro salvezza a scelta su INT o SAG. Ogni uso aggiuntivo nello stesso scontro abbassa la CD. Attualmente in possesso di Gabrael.",nt:"Il vero Estarossa, oggi imprigionato. Non combatte direttamente: SAG al massimo, legge il campo con perfezione millenaria."},
  {nm:"Symael",ae:"Glaciale",rl:"Combattente Heavy · Bilanciato",hp:624,ac:"#7ec8e3",s:{FOR:40,DES:34,COST:38,INT:28,SAG:44,CAR:24},wf:"Alatreon (Lancia Pesante Uncinata)",mech:[["Dado danno","1D8 base, progressione fino a 6D8."]],ar:"Collana del Desufiora",ad:"Comunicazione diretta con qualsiasi Behemoth. Comprende e può rispondere, ma non è obbligato ad obbedire. In combattimento: tentativo di distogliere l'attenzione del Behemoth per 1 turno (CD SAG del Behemoth).",nt:"L'unico Mael con profilo davvero bilanciato. SAG elevatissima per la comunicazione con i Behemoth."},
  {nm:"Azrael",ae:"Oscuro",rl:"Logoramento · Controllo Campo",hp:512,ac:"#8860d0",s:{FOR:30,DES:36,COST:34,INT:46,SAG:40,CAR:22},wf:"Vita Mortale (Falce, Guerra di Logoramento)",mech:[["Accumulo ferite","Ogni colpo aggiunge 1D4 di danno passivo/turno. Cumulativo e permanente."]],ar:"Flauto di Elias Folfo",ad:"Evoca 1D6 fantasmi (PV: 1D12 + bonus SAG di Azrael, spada 1D8). Durano finché non vengono sconfitti. Non riutilizzabile finché almeno un fantasma è in campo.",nt:"Ogni colpo è un investimento. INT (46): calcola quando smettere perché il bersaglio è già morto."},
  {nm:"Raphael",ae:"Ardente",rl:"Artigliere · Lunga Distanza",hp:400,ac:"#e05a20",s:{FOR:22,DES:46,COST:28,INT:50,SAG:34,CAR:44},wf:"Carmilla (Bastone da Passeggio / Fucile Aetherico)",mech:[["Dado danno","Superiore alla pistola aetherica standard. Gittata maggiore, effetti elementali più intensi."]],ar:"Braccio del Mixitron",ad:"Trasformazione in Behemoth ardente meccanico (100 PV fissi). Abbattuta la forma, ricarica 3 turni prima di poter ritrasformarsi.",nt:"Glass cannon: INT e DES al massimo, COST e FOR al minimo."},
  {nm:"Gabrael",ae:"Radiante",rl:"Inganno · Manipolazione della Luce",hp:464,ac:"#b888ff",villain:true,s:{FOR:22,DES:48,COST:36,INT:50,SAG:44,CAR:48},wf:"Tasca Dimensionale (Pugnale, Controllo della Luce)",mech:[["Attivazione","Tocca una superficie riflettente per creare uno specchio aetherico. Più specchi = campo più ampio."],["Difesa","Il nemico crede di avanzare verso Gabrael ma colpisce chiunque Gabrael decida."],["Attacco","Lancia l'attacco verso uno specchio: emerge da una direzione imprevedibile."],["Contromisure","1) Osservare i riflessi (richiede rinunciare al turno). 2) Distruggere tutti gli specchi."]],ar:"Manto di Rinmole",ad:"Nasconde fattezze e intenti. Nessuno può leggere le sue azioni o prepararsi contro di lui. Può assumere le sembianze di chiunque. Non distrutto, al contrario di quanto credono i player.",q:"Gabrael è un enigma da risolvere prima di essere un avversario da sconfiggere.",nt:"⚠ Il villain principale, si spaccia per Estarossa. INT e CAR rotte (50, 48): impossibile da ingannare."},
  {nm:"Mykael",ae:"Folgorante",rl:"DPS Aggressivo · Doppie Spade",hp:704,ac:"#d4b800",s:{FOR:48,DES:46,COST:40,INT:22,SAG:26,CAR:28},wf:"Valstrax (Due Spade, Ibrido Bilanciato/Leggero)",mech:[["Dado danno","1D6 base per spada, progressione fino a 6D6. Secondo attacco quasi sempre disponibile."]],ar:"Armatura del Ragnarok",ad:"Immune a danni fisici e aetherici per 1 turno a scelta, anche fuori dal proprio turno. Ricarica: 3 turni.",nt:"Opposto speculare di Estarossa. Il combattente più puro. Devastante, quasi inarrestabile."}
];
const AD=[
  {nm:"Wils Bormen",ae:"Ascia · Lv.20",rl:"Maestro d'armi · Forgiatore",wp:"Ascia",lv:20,hp:240,ac:"#c8a84b",s:{FOR:21,DES:14,COST:24,INT:20,SAG:18,CAR:16},nt:"COST alta (24) da anni di lavoro alla forgia. SAG e INT elevate per decenni di studio pratico."},
  {nm:"Moyra Heigsketter",ae:"Martello · Lv.20",rl:"Maestra delle armature",wp:"Martello",lv:20,hp:240,ac:"#8b6840",s:{FOR:18,DES:14,COST:24,INT:22,SAG:20,CAR:16},nt:"Più analitica di Wils. COST al massimo per la filosofia difensiva."},
  {nm:"Katerin Sorrel",ae:"Spada · Lv.20",rl:"Maestra della spada",wp:"Spada",lv:20,hp:200,ac:"#7ec8e3",s:{FOR:22,DES:24,COST:20,INT:16,SAG:18,CAR:18},nt:"Probabilmente il miglior duellante puro di Ramsgate."},
  {nm:"Linnea Silver",ae:"Ascia · Lv.20",rl:"Maestra dell'ascia",wp:"Ascia",lv:20,hp:220,ac:"#e05a20",s:{FOR:26,DES:18,COST:22,INT:18,SAG:18,CAR:16},nt:"La più forte fisicamente degli Otto. FOR al massimo teorico."},
  {nm:"Markus Boher",ae:"Martello · Lv.20",rl:"Maestro del martello · Porto",wp:"Martello",lv:20,hp:240,ac:"#a07830",s:{FOR:26,DES:14,COST:24,INT:16,SAG:18,CAR:18},nt:"FOR e COST dominanti. Costruito per fronteggiare direttamente un Behemoth."},
  {nm:"Lady Luck",ae:"Catena · Lv.20",rl:"Maestra della catena",wp:"Lame a Catena",lv:20,hp:180,ac:"#f0d020",s:{FOR:18,DES:26,COST:18,INT:20,SAG:18,CAR:22},nt:"DES al massimo. Non è costruita per assorbire colpi, ma per non essere mai colpita."},
  {nm:"La Maestra Sfregiata",ae:"Pugni · Lv.20",rl:"Maestra dei pugni aetherici",wp:"Pugni Aetherici",lv:20,hp:220,ac:"#8860d0",s:{FOR:20,DES:22,COST:22,INT:16,SAG:26,CAR:14},nt:"SAG al massimo (26): la forza nasce dalla disciplina interiore."},
  {nm:"Xelya",ae:"Lancia · Lv.20",rl:"Maestra della lancia",wp:"Lancia",lv:20,hp:200,ac:"#d4a8ff",s:{FOR:20,DES:24,COST:20,INT:18,SAG:22,CAR:18},nt:"DES dominante per il controllo dello spazio. Parla poco, osserva tutto."}
];
const MND=[
  {nm:"Janek Zai",ae:"Armi da fuoco · Lv.20",rl:"Ammiraglio · Veterano di guerra",wp:"Pistola/Arco Aetherico",lv:20,hp:220,ac:"#f0d020",s:{FOR:18,DES:26,COST:22,INT:18,SAG:22,CAR:18},nt:"Il combattente più pericoloso tra i Minori. Precisione militare affinata in decenni."},
  {nm:"Nonna Yaga",ae:"Botanica · Lv.20",rl:"Esperta di pozioni",wp:"—",lv:20,hp:180,ac:"#8b6840",s:{FOR:10,DES:12,COST:18,INT:26,SAG:26,CAR:18},nt:"INT e SAG massime: un'enciclopedia vivente di conoscenze rare."},
  {nm:"Il Mediatore",ae:"Celle Aetheriche · Lv.18",rl:"Ricercatore · Padre delle Omnicelle",wp:"—",lv:18,hp:162,ac:"#a07830",s:{FOR:10,DES:14,COST:18,INT:26,SAG:22,CAR:14},nt:"⚠ Vera identità: Edgar Solomon. Il suo vero potere non è il combattimento."},
  {nm:"Shaed Priyani",ae:"Behemothologia · Lv.18",rl:"Massima esperta dei Behemoth",wp:"—",lv:18,hp:162,ac:"#8860d0",s:{FOR:12,DES:18,COST:18,INT:24,SAG:26,CAR:16},nt:"SAG al massimo per la lettura comportamentale dei Behemoth."},
  {nm:"Gregorio Flynt",ae:"Risorse · Lv.16",rl:"Il Gregario · Veterano",wp:"Generico",lv:16,hp:160,ac:"#c8a84b",s:{FOR:20,DES:18,COST:20,INT:16,SAG:18,CAR:20},nt:"Estremamente equilibrato e carismatico. La sua forza è l'affidabilità."},
  {nm:"Tressa",ae:"Sociale · Lv.16",rl:"Barista · Cuore di Ramsgate",wp:"—",lv:16,hp:128,ac:"#e05a20",s:{FOR:10,DES:14,COST:16,INT:18,SAG:22,CAR:24},nt:"CAR dominante. La sua influenza deriva dalla capacità di comprendere le persone."},
  {nm:"Arkan Drew",ae:"Inventore · Lv.16",rl:"Ingegnere · Prototipista",wp:"Prototipi Meccanici",lv:16,hp:128,ac:"#7ec8e3",s:{FOR:10,DES:12,COST:16,INT:26,SAG:20,CAR:14},nt:"INT al massimo. Con i suoi prototipi può cambiare il corso di una battaglia."},
  {nm:"Ozz l'Onesto",ae:"Corriere · Lv.10",rl:"Messaggero · Esploratore urbano",wp:"—",lv:10,hp:90,ac:"#d4b800",s:{FOR:12,DES:20,COST:18,INT:14,SAG:18,CAR:22},nt:"Il più umano del gruppo. Conosce Ramsgate come le proprie tasche."}
];
