/* Sezione: I Mael — testo e struttura HTML.
   Viene inserita nella pagina esattamente nel punto in cui index.html la richiama. */
tcjSezione(`<section id="mael">
  <div class="si">
    <div class="sh"><div class="sl">Figure Leggendarie</div><h2 class="st">I Mael</h2><div class="sline"></div><p class="sdesc">Slayer che hanno stretto un patto con il Maelstrom e forgiato artefatti personali. La missione: recuperare gli artefatti perduti.</p></div>
    <div class="qi" style="max-width:800px;margin:0 auto 2.5rem">Estarossa ha rivelato l'esistenza dei Mael e dei loro artefatti. La missione è recuperare questi oggetti di potere, dispersi dopo il Tradimento.<br><span style="font-size:.85rem">Sotto ogni artefatto ancora disperso trovate un riquadro libero: annotate lì dove sospettate si trovi. Resta salvato in questo browser.</span></div>
    <div class="ml-bar"><button type="button" class="nv-tog" id="ml-tog" onclick="mlAll()">💎 Mostra tutti i Mael</button></div><div class="ml-wrap" id="ml-wrap"><div class="ml-sym"><img src="media/mael-simbolo.webp" alt="Il simbolo dei sei Mael" draggable="false"><button type="button" class="ml-gem" data-k="gabrael" aria-label="Gabrael" style="left:49.82%;top:16.21%;width:17.71%;--gc:#fff1c9"></button><button type="button" class="ml-gem" data-k="symael" aria-label="Symael" style="left:18.63%;top:34.52%;width:17.71%;--gc:#6ec6ff"></button><button type="button" class="ml-gem" data-k="mykael" aria-label="Mykael" style="left:79.89%;top:34.52%;width:17.71%;--gc:#ffd84a"></button><button type="button" class="ml-gem" data-k="maelstrom" aria-label="Il Maelstrom" style="left:50.00%;top:49.76%;width:33.95%;--gc:#a6e6ff"></button><button type="button" class="ml-gem" data-k="estarossa" aria-label="Estarossa" style="left:18.63%;top:68.07%;width:17.71%;--gc:#6fdc6a"></button><button type="button" class="ml-gem" data-k="raphael" aria-label="Raphael" style="left:79.89%;top:68.07%;width:17.71%;--gc:#ff4a3a"></button><button type="button" class="ml-gem" data-k="azrael" aria-label="Azrael" style="left:49.82%;top:84.60%;width:17.71%;--gc:#b07cff"></button></div><div class="ml-cards" id="ml-cards"><div class="ml-hint">Passa sopra una gemma<br>per evocare il suo Mael</div><div class="card" data-a="neutro" data-mk="maelstrom"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Il Maelstrom</div><span class="tag tn">Origine</span></div><div class="cb"><p>Nato con la Frantumazione, nell'Anno 0, è la forza da cui ebbero origine le Isole Frantumate.</p><p>Con esso i sei Mael strinsero il loro patto. Durante il Tradimento i fratelli si combatterono per ascendere al suo rango.</p></div></div>
      <div class="card" data-mk="estarossa" data-a="terrestre"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Estarossa</div><span class="tag tt">Terrestre</span></div><div style="font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.14em;color:var(--gold3);text-transform:uppercase;margin-bottom:.25rem">Artefatto</div><div style="font-family:'Cinzel',serif;font-size:.88rem;color:var(--gold2);margin-bottom:.25rem">Corona del Capricus</div><div style="font-size:.85rem;color:var(--text2);font-style:italic">Posizione attuale sconosciuta.</div><div style="margin-top:.7rem;padding:.55rem;background:rgba(var(--gold-rgb),.04);border:1px solid var(--border);font-size:.8rem;color:var(--text2)">📍 Governa Ramsgate</div></div>
      <div class="card" data-mk="symael" data-a="glaciale"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Symael</div><span class="tag tg">Glaciale</span></div><div style="font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.14em;color:var(--gold3);text-transform:uppercase;margin-bottom:.25rem">Artefatto</div><div style="font-family:'Cinzel',serif;font-size:.88rem;color:var(--gold2);margin-bottom:.25rem">Collana del Desufiora</div><div style="font-size:.85rem;color:var(--text2);font-style:italic">Da recuperare.</div><div class="ml-hyp"><div class="ml-hlbl"><span>🔍 Ipotesi del gruppo</span><span class="ml-hsv" id="ml-sv-symael"></span></div><textarea class="ml-hin" id="ml-symael" rows="2" placeholder="Dove pensate si trovi la Collana…" oninput="mlSave('symael')"></textarea></div></div>
      <div class="card" data-mk="azrael" data-a="oscuro"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Azrael</div><span class="tag to">Oscuro</span></div><div style="font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.14em;color:var(--gold3);text-transform:uppercase;margin-bottom:.25rem">Artefatto</div><div style="font-family:'Cinzel',serif;font-size:.88rem;color:var(--gold2);margin-bottom:.25rem">Flauto di Elias Folfo</div><div style="font-size:.85rem;color:var(--text2);font-style:italic">Da recuperare.</div><div class="ml-hyp"><div class="ml-hlbl"><span>🔍 Ipotesi del gruppo</span><span class="ml-hsv" id="ml-sv-azrael"></span></div><textarea class="ml-hin" id="ml-azrael" rows="2" placeholder="Dove pensate si trovi il Flauto…" oninput="mlSave('azrael')"></textarea></div></div>
      <div class="card" data-mk="raphael" data-a="ardente"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Raphael</div><span class="tag ta">Ardente</span></div><div style="font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.14em;color:var(--gold3);text-transform:uppercase;margin-bottom:.25rem">Artefatto</div><div style="font-family:'Cinzel',serif;font-size:.88rem;color:var(--gold2);margin-bottom:.25rem">Braccio del Mixitron</div><div style="font-size:.85rem;color:var(--text2);font-style:italic">Da recuperare.</div><div class="ml-hyp"><div class="ml-hlbl"><span>🔍 Ipotesi del gruppo</span><span class="ml-hsv" id="ml-sv-raphael"></span></div><textarea class="ml-hin" id="ml-raphael" rows="2" placeholder="Dove pensate si trovi il Braccio…" oninput="mlSave('raphael')"></textarea></div></div>
      <div class="card" data-mk="gabrael" data-a="radiante" style="opacity:.75"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Gabrael</div><span class="tag tr">Radiante</span></div><div style="font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.14em;color:var(--gold3);text-transform:uppercase;margin-bottom:.25rem">Artefatto</div><div style="font-family:'Cinzel',serif;font-size:.88rem;color:var(--text2);margin-bottom:.25rem">Manto di Rinmole</div><div style="font-size:.85rem;color:var(--fire);font-style:italic">⚠ Distrutto durante il Tradimento.</div></div>
      <div class="card" data-mk="mykael" data-a="folgorante"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:.9rem"><div class="ct">Mykael</div><span class="tag tf">Folgorante</span></div><div style="font-family:'Cinzel',serif;font-size:.6rem;letter-spacing:.14em;color:var(--gold3);text-transform:uppercase;margin-bottom:.25rem">Artefatto</div><div style="font-family:'Cinzel',serif;font-size:.88rem;color:var(--gold2);margin-bottom:.25rem">Armatura del Ragnarok</div><div style="font-size:.85rem;color:var(--text2);font-style:italic">Da recuperare.</div><div class="ml-hyp"><div class="ml-hlbl"><span>🔍 Ipotesi del gruppo</span><span class="ml-hsv" id="ml-sv-mykael"></span></div><textarea class="ml-hin" id="ml-mykael" rows="2" placeholder="Dove pensate si trovi l’Armatura…" oninput="mlSave('mykael')"></textarea></div></div>
    </div></div>
  </div>
</section>`);
