/* Sezione: Il Mondo — testo e struttura HTML.
   Viene inserita nella pagina esattamente nel punto in cui index.html la richiama. */
tcjSezione(`<section id="mondo" style="display:none">
  <div class="si">
    <div class="sh"><div class="sl">Lore</div><h2 class="st">Le Isole Frantumate</h2><div class="sline"></div><p class="sdesc">Sei isole fluttuanti, ognuna plasmata da un Aether dominante, ognuna con la propria storia di potere, conflitto e sopravvivenza.</p></div>
    <div class="g2">
      <div class="card" data-a="glaciale"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(126,200,227,.1);color:var(--ice);display:flex;align-items:center;justify-content:center;font-size:1.1rem">❄️</div><div><div class="ct">Continente Glaciale</div><div class="cs">Capitale: NetherWinter</div></div></div><div class="cb"><p>Dominate dalla monarchia assoluta della <strong>Famiglia Silver</strong>, guidata dal tiranno <strong>Ragnar Silver</strong>. Un tempo regno cosmopolita e aperto, si è trasformato in uno stato militarista. Il regime Silver esercita il dominio da circa cinque decadi, con un accordo con le Guardie di Ostia per lo scambio di tecnologie militari.</p><div class="qi">Ispirazione culturale: Medioevo occidentale europeo.</div></div><span class="tag tg">❄ Glaciale</span></div>
      <div class="card" data-a="folgorante"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(240,208,32,.1);color:var(--lightning);display:flex;align-items:center;justify-content:center;font-size:1.1rem">⚡</div><div><div class="ct">Continente Folgorante</div><div class="cs">Capitale: Ostia</div></div></div><div class="cb"><p>Una distopia steampunk industriale governata con pugno di ferro dalle <strong>Guardie di Ostia</strong> di <strong>Godrik E. Tasher</strong>. I <strong>TecnoSlayer</strong> — robot che mimano le capacità degli Slayer — sono prodotti in massa. I ribelli <strong>Eroi di Ostia</strong> sabotano le fabbriche per fermare l'espansionismo del continente e la sua corsa alle armi.</p><div class="qi">Sopravvive la scuola dei Monaci del Pugno, di cui faceva parte la Maestra Sfregiata.</div></div><span class="tag tf">⚡ Folgorante</span></div>
      <div class="card" data-a="terrestre"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(139,104,64,.1);color:var(--earth);display:flex;align-items:center;justify-content:center;font-size:1.1rem">🌍</div><div><div class="ct">Continente Terrestre</div><div class="cs">Capitale: Greenshard</div></div></div><div class="cb"><p>Due anime: gli <strong>Slayer di Frontiera</strong>, aperti e pacifici, e i <strong>Custodi di Rovo</strong>, radicali che non tollerano estranei. Una scissione nata dalla disputa tra i figli di Ermonium Baalz. I Custodi di Rovo subiscono la minaccia crescente dell'<strong>Agarus</strong>.</p></div><span class="tag tt">🌍 Terrestre</span></div>
      <div class="card" data-a="ardente"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(224,90,32,.1);color:var(--fire);display:flex;align-items:center;justify-content:center;font-size:1.1rem">🔥</div><div><div class="ct">Continente Ardente</div><div class="cs">Capitale: Nuova Amorgoth</div></div></div><div class="cb"><p>Due tribù Krolachi convivono dopo aver perso le proprie capitali: gli <strong>Amorlarien</strong> (guerrieri viscerali) e i <strong>Gothzian</strong> (calcolatori e schivi). <strong>Salaman Rebenek</strong> guida la comunità mentre tratta un'alleanza militare con le Isole Congelanti.</p></div><span class="tag ta">🔥 Ardente</span></div>
      <div class="card" data-a="radiante"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(212,168,255,.1);color:var(--radiant);display:flex;align-items:center;justify-content:center;font-size:1.1rem">✨</div><div><div class="ct">Continente Radiante</div><div class="cs">Terra di Nessuno</div></div></div><div class="cb"><p>Una terra desolata: altopiani di rocce secche, dominati dai pirati nelle zone periferiche. Le leggende parlano dei <strong>Solcavuoto</strong> — una civiltà antica mai provata concretamente. I <strong>Paradossisti</strong> e i <strong>Primordialisti</strong> sopravvivono nell'interno. A <strong>Rupenigma</strong> si dice sia nascosto qualcosa di antico.</p></div><span class="tag tr">✨ Radiante</span></div>
      <div class="card" data-a="oscuro"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(136,96,208,.1);color:var(--dark);display:flex;align-items:center;justify-content:center;font-size:1.1rem">🌑</div><div><div class="ct">Continente Oscuro</div><div class="cs">Capitale: Zoa Shia</div></div></div><div class="cb"><p>Avvolte nell'oscurità, governate da un sistema feudale basato sul baratto. Il prestigio dipende dalle capacità dimostrabili. Famiglie principali: <strong>Zeraora, Grimstone, Val’Riden, Monkuiced</strong>. Gli <strong>Slayer Fatui</strong> — uniformi a fiamme violacee — sono la compagnia dei <strong>Monkuiced</strong>; gli <strong>Slayer Ombra</strong> quella dei <strong>Val’Riden</strong>. Entrambe vendono i propri servizi a chiunque possa pagarli.</p><div class="qi">Ispirazione: Medioevo giapponese, cinese e mongolo.</div></div><span class="tag to">🌑 Oscuro</span></div>
    </div>
    <div style="max-width:900px;margin:2rem auto 0"><div class="card" data-a="neutro" style="padding:1.75rem"><div style="display:flex;align-items:center;gap:.75rem;margin-bottom:.75rem"><div style="width:36px;height:36px;border-radius:50%;background:rgba(var(--gold-rgb),.1);color:var(--gold);display:flex;align-items:center;justify-content:center;font-size:1.1rem">🏰</div><div><div class="ct">Ramsgate — Baluardo degli Slayer</div><div class="cs">Governata da Estarossa, Mael dell'Aether Terrestre</div></div></div><div class="cb"><p>Città simbolo degli Slayer, distrutta durante il cataclisma del Tradimento e ricostruita sulle sue rovine. Cosmopolita per eccellenza. Ramsgate regola il rilascio del titolo ufficiale di Slayer. L'unica zona vietata è l'isola della <strong>Vecchia Ramsgate</strong>: le scariche di aether puro la rendono altamente instabile.</p></div><span class="tag tgo">Neutro</span></div></div>
  </div>
</section>`);
