/* Sezione: Maestri di Ramsgate (NPC) — testo e struttura HTML.
   Viene inserita nella pagina esattamente nel punto in cui index.html la richiama. */
tcjSezione(`<section id="npc">
  <div class="si">
    <div class="sh"><div class="sl">Personaggi Non Giocanti</div><h2 class="st">I Maestri di Ramsgate</h2><div class="sline"></div><p class="sdesc">Figure chiave della Gilda e della città. Tocca un nome per aprirne la scheda.</p></div>
    <div class="bbox" id="bbox-npc"><div class="ndiv">Otto Alti Maestri</div>
    <div class="mae-list"><button type="button" class="card mae-it" data-i="0" aria-haspopup="dialog"><span class="ct">Wils Bormen</span><span class="mae-r">Maestro d&#x27;armi — forgiatore ufficiale</span></button><button type="button" class="card mae-it" data-i="1" aria-haspopup="dialog"><span class="ct">Moyra Heigsketter</span><span class="mae-r">Maestra delle armature</span></button><button type="button" class="card mae-it" data-i="2" aria-haspopup="dialog"><span class="ct">Katerin Sorrel</span><span class="mae-r">Maestra della spada</span></button><button type="button" class="card mae-it" data-i="3" aria-haspopup="dialog"><span class="ct">Linnea Silver</span><span class="mae-r">Maestra dell&#x27;ascia</span></button><button type="button" class="card mae-it" data-i="4" aria-haspopup="dialog"><span class="ct">Markus Boher</span><span class="mae-r">Maestro del martello — navi e porto</span></button><button type="button" class="card mae-it" data-i="5" aria-haspopup="dialog"><span class="ct">Lady Luck</span><span class="mae-r">Maestra della catena — economia degli Slayer</span></button><button type="button" class="card mae-it" data-i="6" aria-haspopup="dialog"><span class="ct">La Maestra Sfregiata</span><span class="mae-r">Maestra dei pugni aetherici</span></button><button type="button" class="card mae-it" data-i="7" aria-haspopup="dialog"><span class="ct">Xelya</span><span class="mae-r">Maestra della lancia</span></button></div>
    <div class="ndiv">Otto Maestri Minori</div>
    <div class="mae-list"><button type="button" class="card mae-it" data-i="8" aria-haspopup="dialog"><span class="ct">Il Mediatore</span><span class="mae-r">Esperto di celle aetheriche</span></button><button type="button" class="card mae-it" data-i="9" aria-haspopup="dialog"><span class="ct">Arkan Drew</span><span class="mae-r">Inventore e scienziato</span></button><button type="button" class="card mae-it" data-i="10" aria-haspopup="dialog"><span class="ct">Shaed Priyani</span><span class="mae-r">Esperta di behemothologia</span></button><button type="button" class="card mae-it" data-i="11" aria-haspopup="dialog"><span class="ct">Janek Zai</span><span class="mae-r">Esperto di armi da fuoco</span></button><button type="button" class="card mae-it" data-i="12" aria-haspopup="dialog"><span class="ct">Gregorio Flynt</span><span class="mae-r">Materiali rari</span></button><button type="button" class="card mae-it" data-i="13" aria-haspopup="dialog"><span class="ct">Ernest “Ozz” Honest</span><span class="mae-r">Messaggero</span></button><button type="button" class="card mae-it" data-i="14" aria-haspopup="dialog"><span class="ct">Tressa</span><span class="mae-r">Barista della Coda di Gnasher</span></button><button type="button" class="card mae-it" data-i="15" aria-haspopup="dialog"><span class="ct">Nonna Yaga</span><span class="mae-r">Esperta di pozioni e botanica</span></button></div>
</div>
  </div>
</section>`);
