/* Sezione: Scheda personaggio e Area dello Slayer — testo e struttura HTML.
   Viene inserita nella pagina esattamente nel punto in cui index.html la richiama. */
tcjSezione(`<section id="scheda" style="background:var(--bg2)">
  <div class="si">
    <div class="sh"><div class="sl">Area dello Slayer</div><h2 class="st" id="pa-title">The Careless Journey</h2><div class="sline"></div><p class="sdesc">Licenza, scheda e note personali. Ogni area si apre con il codice del proprio Slayer e si salva da sola in questo browser.</p></div>
<link rel="stylesheet" href="css/10-scheda.css">
<div class="sc-tabs" id="sc-tabs"></div>
<div class="pa-gate" id="pa-gate" style="display:none"><div class="pa-gate-seal" id="pa-gate-seal">🔒</div><div class="pa-gate-t">Area sigillata</div><div class="pa-gate-s">Inserisci il codice di <b id="pa-gate-nm">—</b> per aprire la sua area.</div><input type="password" class="pa-gate-in" id="pa-code" placeholder="Codice" autocomplete="off" onkeydown="if(event.key==='Enter')paTry()"><button class="pa-gate-btn" type="button" onclick="paTry()">Apri l'area</button><div class="pa-gate-err" id="pa-gate-err">Codice errato. Riprova.</div></div>
<div id="pa-body">
<div class="pa-bar"><span class="pa-status" id="pa-status">Salvataggio automatico attivo</span><button class="bk-btn" type="button" id="pa-lockbtn" onclick="paLock()">🔒 Chiudi l'area</button></div>
<div class="sc-wrap">
  <div class="sc-card sc-full pa-id">
    <div class="pa-id-head"><div><div class="pa-id-kick">Ramsgate · Registro degli Slayer</div><div class="pa-id-title">Licenza dello Slayer</div></div><div class="pa-id-seal" id="pa-id-seal">✦</div></div>
    <div class="pa-id-grid">
      <div><div class="pa-phw"><span class="pa-co pc-tl"></span><span class="pa-co pc-tr"></span><span class="pa-co pc-bl"></span><span class="pa-co pc-br"></span><label class="pa-ph" id="pa-ph" for="pa-portrait-file"><img id="pa-portrait" alt="Ritratto"><span>+ Aggiungi ritratto</span></label></div><div class="pa-seal" id="pa-seal" style="display:none"><button type="button" class="pa-seal-vis" id="pa-seal-vis" onclick="sealToggle()" aria-label="Personalizza il sigillo del rango"></button><div class="pa-seal-ctl" id="pa-seal-ctl" hidden><div class="pa-seal-nm">Sigillo · <span id="pa-seal-nm"></span></div><label>Cera <input type="color" id="pa-seal-w" oninput="sealSet('w',this.value)"></label><label>Logo <input type="color" id="pa-seal-l" oninput="sealSet('l',this.value)"></label><button type="button" class="pa-seal-reset" id="pa-seal-reset" onclick="sealReset()">↺ Colori di base</button></div></div><input type="file" id="pa-portrait-file" accept="image/*" style="display:none" onchange="paPortrait(this)"><button class="pa-mini" type="button" id="pa-ph-del" onclick="paPortraitDel()">Rimuovi ritratto</button></div>
      <div class="pa-fields">
        <div class="pa-f full"><label for="pa-id-nome">Nome completo</label><input id="pa-id-nome" class="pa-name" placeholder="Nome e cognome"></div>
        <div class="pa-f"><label for="pa-id-titolo">Soprannome / Titolo</label><input id="pa-id-titolo" placeholder="Come ti chiamano"></div>
        <div class="pa-f"><label for="pa-id-eta">Età</label><input id="pa-id-eta" inputmode="numeric" placeholder="—"></div>
        <div class="pa-f"><label for="pa-id-giorno">Nato il</label><div class="pa-born"><input id="pa-id-giorno" type="number" min="1" max="30" placeholder="gg"><select id="pa-id-triade"><option value="">— triade —</option><option value="Radiante">Triade Radiante</option><option value="Folgorante">Triade Folgorante</option><option value="Ardente">Triade Ardente</option><option value="Terrestre">Triade Terrestre</option><option value="Congelante">Triade Congelante</option><option value="Oscura">Triade Oscura</option><option value="Alborea">Triade Alborea</option><option value="Tuonante">Triade Tuonante</option><option value="Fiammeggiante">Triade Fiammeggiante</option><option value="Sporizzata">Triade Sporizzata</option><option value="Algente">Triade Algente</option><option value="Foscomanto">Triade Foscomanto</option></select></div></div>
        <div class="pa-f"><label for="pa-id-aether">Aether di affinità</label><select id="pa-id-aether"><option value="">— scegli —</option><option value="glaciale">❄ Glaciale</option><option value="ardente">🔥 Ardente</option><option value="folgorante">⚡ Folgorante</option><option value="terrestre">🌍 Terrestre</option><option value="radiante">✨ Radiante</option><option value="oscuro">🌑 Oscuro</option><option value="neutro">◆ Neutro</option></select></div>
        <div class="pa-f"><label for="pa-id-continente">Continente d'origine</label><select id="pa-id-continente"><option value="">— scegli —</option><option value="glaciale">❄️ Continente Glaciale</option><option value="ardente">🔥 Continente Ardente</option><option value="folgorante">⚡ Continente Folgorante</option><option value="terrestre">🌍 Continente Terrestre</option><option value="radiante">✨ Continente Radiante</option><option value="oscuro">🌑 Continente Oscuro</option><option value="ramsgate">⚓ Ramsgate</option><option value="ignoto">❔ Ignoto</option></select></div>
        <div class="pa-f"><label for="pa-id-terra">Terra natale</label><input id="pa-id-terra" placeholder="Città, regione, isola…"></div>
        <div class="pa-f full"><label for="pa-id-casata">Casata / Affiliazione</label><input id="pa-id-casata" placeholder="Famiglia, clan, compagnia…"></div>
        <div class="pa-f full"><label for="pa-id-segni">Segni particolari</label><textarea id="pa-id-segni" rows="2" placeholder="Cicatrici, tatuaggi, portamento…"></textarea></div>
        <div class="pa-f full"><label for="pa-id-motto">Motto</label><input id="pa-id-motto" class="pa-motto" placeholder="Una frase che ti rappresenta"></div>
      </div>
    </div>
    <div class="pa-id-foot"><span>N° <b id="pa-id-num">TCJ</b></span><span>Rilasciata a Ramsgate</span></div>
  </div>
  <div class="sc-card sc-full"><div style="display:grid;grid-template-columns:1fr 2fr 1fr 1fr;gap:.85rem;align-items:end"><div><span class="sc-lbl">Livello</span><input class="sc-in" id="sc-lvl" type="number" placeholder="1" style="text-align:center;font-size:1.1rem"></div><div><span class="sc-lbl">Rango Slayer</span><select class="sc-in" id="sc-rango" style="font-family:'Cinzel',serif;font-size:.78rem;letter-spacing:.06em;cursor:pointer;padding:.32rem .5rem"><option value="">— seleziona rango —</option><option value="novizio">⚪ Novizio (Lv. 1–5)</option><option value="cacciatore">🟤 Cacciatore (Lv. 6–10)</option><option value="discepolo">🔵 Discepolo (Lv. 11–15)</option><option value="maestro">🟡 Maestro (Lv. 16–20)</option><option value="fenice">🔴 Fenice (Lv. 21–30)</option></select></div><div><span class="sc-lbl">Benny</span><div class="sc-counter" style="margin-top:.45rem"><button class="sc-cnt-btn" onclick="scBennyCnt(-1)">−</button><input class="sc-cnt-val" id="sc-benny" type="number" value="0" min="0"><button class="sc-cnt-btn" onclick="scBennyCnt(1)">+</button></div></div><div><span class="sc-lbl">Ispirazioni</span><div class="sc-counter" style="margin-top:.45rem"><button class="sc-cnt-btn" onclick="scInspCnt(-1)">−</button><input class="sc-cnt-val" id="sc-ispirazione" type="number" value="0" min="0"><button class="sc-cnt-btn" onclick="scInspCnt(1)">+</button></div></div></div></div>
  <div class="sc-card"><span class="sc-lbl">Punti Vita</span><input class="sc-pv-box" id="sc-pv" type="text" placeholder="—"></div>
  <div class="sc-card"><span class="sc-lbl">Malus Attivi</span><textarea class="sc-in" id="sc-malus" rows="4" style="resize:none;font-size:.85rem" placeholder="Malus e stati alterati..."></textarea></div>
  <div class="sc-card sc-full"><span class="sc-lbl">Statistiche — Valore · Modificatore</span><div class="sc-stat-row"><div id="sc-stats-left"></div><div id="sc-stats-right"></div></div></div>
  <div class="sc-card sc-full"><div class="sc-comp-head"><span class="sc-lbl">Competenze</span><label class="sc-bonus"><span>Bonus Competenza</span><input type="number" id="sc-comp-bonus" value="2" oninput="scRecalc()"></label></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:.15rem .75rem;margin-top:.25rem" id="sc-comps-grid"></div></div>
  <div class="sc-card"><span class="sc-lbl">Arma Principale</span><input class="sc-in" id="sc-arma" placeholder="Nome arma..." style="margin-bottom:.5rem"><select class="sc-in sc-wsel" id="sc-wcat" aria-label="Categoria dell’arma"></select><span class="sc-lbl">Cariche Aetheriche</span><div style="display:flex;flex-direction:column;gap:.4rem"><div style="display:flex;gap:.4rem" id="sc-ch-r1"></div><div style="display:flex;gap:.4rem" id="sc-ch-r2"></div></div></div>
  <div class="sc-card"><span class="sc-lbl">Abilità Arma</span><div class="sc-winfo" id="sc-winfo"></div><textarea class="sc-in" id="sc-abil" rows="2" style="resize:vertical;font-size:.88rem;margin-top:.6rem" placeholder="Note personali sull’arma..."></textarea></div>
  <div class="sc-card" style="display:flex;flex-direction:column;gap:.75rem">
    <div><span class="sc-lbl">Nucleo Attacco</span><div class="sc-nrow"><canvas class="sc-orb" id="orb-att" width="88" height="88" aria-hidden="true"></canvas><div class="sc-ncol"><div class="sc-ndisp" id="sc-natt-d"></div><select class="sc-nsel" id="sc-natt-s" onchange="scNucleo('att');orbSet('att',this.value)"><option value="">— nessuno</option><option value="glaciale">❄ Glaciale</option><option value="ardente">🔥 Ardente</option><option value="folgorante">⚡ Folgorante</option><option value="terrestre">🌍 Terrestre</option><option value="radiante">✨ Radiante</option><option value="oscuro">🌑 Oscuro</option></select></div></div></div>
    <div><span class="sc-lbl">Nucleo Difesa</span><div class="sc-nrow"><canvas class="sc-orb" id="orb-def" width="88" height="88" aria-hidden="true"></canvas><div class="sc-ncol"><div class="sc-ndisp" id="sc-ndef-d"></div><select class="sc-nsel" id="sc-ndef-s" onchange="scNucleo('def');orbSet('def',this.value)"><option value="">— nessuno</option><option value="glaciale">❄ Glaciale</option><option value="ardente">🔥 Ardente</option><option value="folgorante">⚡ Folgorante</option><option value="terrestre">🌍 Terrestre</option><option value="radiante">✨ Radiante</option><option value="oscuro">🌑 Oscuro</option></select></div></div></div>
  </div>
  <div class="sc-card"><span class="sc-lbl">Arma Secondaria</span><input class="sc-in" id="sc-arma2" placeholder="Nome arma..." style="margin-bottom:.5rem"><div class="sc-a2t"><label><input type="radio" name="sc-a2t" value="pistola" onchange="document.getElementById('sc-arma2t').value='pistola';document.getElementById('sc-arma2t').dispatchEvent(new Event('change',{bubbles:true}))"><span>🔫 Pistola</span></label><label><input type="radio" name="sc-a2t" value="arco" onchange="document.getElementById('sc-arma2t').value='arco';document.getElementById('sc-arma2t').dispatchEvent(new Event('change',{bubbles:true}))"><span>🏹 Arco</span></label></div><input type="hidden" id="sc-arma2t" value="pistola"><input type="hidden" id="sc-ammo-log" value=""><div class="sc-ammo-head"><span class="sc-lbl" id="sc-ammo-lbl">Proiettili</span><button type="button" class="sc-ammo-reset" onclick="ammoReset()">↺ Reset</button></div><div class="sc-ammo" id="sc-ammo"></div><div class="sc-ammo-last" id="sc-ammo-last"></div><div class="sc-counter sc-ammo-cnt"><button class="sc-cnt-btn" onclick="scCnt(-1)" aria-label="Togli">−</button><input class="sc-cnt-val" id="sc-proiettili" type="number" value="6" min="0" max="6"><button class="sc-cnt-btn" onclick="scCnt(1)" aria-label="Aggiungi">+</button></div></div>
  <div class="sc-card sc-full"><span class="sc-lbl">Equipaggiamento</span><div style="display:flex;flex-direction:column;gap:.4rem">
    <div style="display:flex;align-items:center;gap:.4rem"><button class="sc-cnt-btn" onclick="scEqCnt(0,-1)">−</button><input class="sc-cnt-val" id="sc-eq-cnt-0" type="number" value="0" min="0" style="width:44px"><button class="sc-cnt-btn" onclick="scEqCnt(0,1)">+</button><input class="sc-in" id="sc-eq-txt-0" placeholder="Tonico / Pilone..." style="flex:1;font-size:.85rem"></div>
    <div style="display:flex;align-items:center;gap:.4rem"><button class="sc-cnt-btn" onclick="scEqCnt(1,-1)">−</button><input class="sc-cnt-val" id="sc-eq-cnt-1" type="number" value="0" min="0" style="width:44px"><button class="sc-cnt-btn" onclick="scEqCnt(1,1)">+</button><input class="sc-in" id="sc-eq-txt-1" placeholder="Tonico / Pilone..." style="flex:1;font-size:.85rem"></div>
    <div style="display:flex;align-items:center;gap:.4rem"><button class="sc-cnt-btn" onclick="scEqCnt(2,-1)">−</button><input class="sc-cnt-val" id="sc-eq-cnt-2" type="number" value="0" min="0" style="width:44px"><button class="sc-cnt-btn" onclick="scEqCnt(2,1)">+</button><input class="sc-in" id="sc-eq-txt-2" placeholder="Tonico / Pilone..." style="flex:1;font-size:.85rem"></div>
    <div style="display:flex;align-items:center;gap:.4rem"><button class="sc-cnt-btn" onclick="scEqCnt(3,-1)">−</button><input class="sc-cnt-val" id="sc-eq-cnt-3" type="number" value="0" min="0" style="width:44px"><button class="sc-cnt-btn" onclick="scEqCnt(3,1)">+</button><input class="sc-in" id="sc-eq-txt-3" placeholder="Tonico / Pilone..." style="flex:1;font-size:.85rem"></div>
  </div></div>
  <div class="sc-card sc-full"><span class="sc-lbl">Inventario</span><textarea class="sc-in" id="sc-equip" rows="3" style="resize:vertical;font-size:.88rem" placeholder="Oggetti, pozioni, strumenti..."></textarea></div>
  <div class="sc-card sc-full"><span class="sc-lbl">💰 Monete</span>
    <div style="display:flex;flex-direction:column;gap:1rem;margin-top:.2rem">
      <div>
        <span class="sc-coin-sub">Monete di Squadra · Totale</span>
        <input class="sc-in" id="sc-coin-team" type="text" inputmode="numeric" placeholder="0" style="text-align:center;font-family:'Cinzel Decorative',serif;font-size:1.1rem;color:var(--gold2)">
      </div>
      <div>
        <span class="sc-coin-sub">Valute</span>
        <div id="sc-coin-rows" style="display:flex;flex-direction:column;gap:.4rem"></div>
        <button class="sc-coin-add" type="button" onclick="sfxPlay('coin');scCoinAdd()">+ Aggiungi valuta</button>
      </div>
      <div>
        <span class="sc-coin-sub">Quota Personale del Personaggio</span>
        <input class="sc-in" id="sc-coin-personal" type="text" inputmode="numeric" placeholder="0" style="text-align:center;font-family:'Cinzel Decorative',serif;font-size:1.1rem;color:var(--gold2)">
      </div>
    </div>
  </div>
  <div class="sc-card sc-full"><span class="sc-lbl">Celle Equipaggiate</span><div class="sc-celle-grid" id="sc-celle"></div></div>
  <div class="sc-card sc-full"><div class="cr-head"><span class="sc-lbl" style="margin:0">Corone Aetheriche</span><span class="cr-meta">Possedute <b id="cr-count">0</b> / 12 &middot; Introito <b id="cr-mult">&mdash;</b></span></div><div class="cr-grid" id="cr-grid"></div><div style="font-size:.74rem;color:var(--text2);margin-top:.6rem;font-style:italic">Clicca una Corona per aprirne la scheda; il quadratino in alto a destra segna il possesso.</div></div>
  <div class="sc-card sc-full"><div class="pa-notes-head"><span class="sc-lbl">Note personali</span><span class="pa-hint">Titoli modificabili · sezioni da aggiungere, spostare, eliminare</span></div><div id="pa-notes"></div><button class="sc-coin-add" type="button" onclick="paNoteAdd()">+ Aggiungi sezione</button></div>
  <div class="sc-card sc-full"><span class="sc-lbl">Backup dei dati</span>
    <div class="bk-row">
      <button class="bk-btn" type="button" onclick="bkExport()">⬇ Scarica backup</button>
      <button class="bk-btn" type="button" onclick="document.getElementById('bk-file').click()">⬆ Ripristina da file</button>
      <input type="file" id="bk-file" accept=".json,application/json" style="display:none" onchange="bkPick(this)">
    </div>
    <div class="bk-msg" id="bk-msg">Salva in un file tutto ciò che il sito tiene in questo browser: le schede dei tre Slayer, le Corone, le note personali e del Master, la nave. Tienilo da parte: se svuoti i dati del browser o cambi computer, è l’unico modo per recuperare tutto.</div>
  </div>
  <button class="sc-save" id="sc-savebtn" onclick="scSave()">Salva Scheda</button>
</div>
</div><!-- /pa-body -->
  </div>
<div class="cr-ov" id="cr-ov" onclick="if(event.target===this)crClose()"><div class="cr-mod"><button class="cr-x" type="button" onclick="crClose()" title="Chiudi">&times;</button><img class="cr-mimg" id="cr-mimg" alt=""><div class="cr-mnm" id="cr-mnm"></div><div class="cr-mds" id="cr-mds"></div><button class="cr-mbtn" id="cr-mbtn" type="button" onclick="crTogCur()"></button></div></div>
</section>`);
